# Change File Names
filename = "hcrc_drupal.xml"

# Converting drupal xml output to SOLR document structure.
replace_xml = '<add>'
replace_records = ''
replace_record = '<doc>'
replace_source_app = ''
replace_style = ''
replace_type = '<field name="type">'
replace_contributors = ''
replace_translated_authors = '<field name="corp_author">'
replace_authors = ''
replace_author = '<field name="author">'
replace_titles = ''
replace_title = '<field name="title">'
replace_keywords = ''
replace_keyword = '<field name="keywords">'
replace_dates = ''
replace_year = '<field name="year">'
replace_pub_dates = ''
replace_date = '<field name="date">'
replace_publisher = '<field name="publisher">'
replace_pub_location = '<field name="pub_place">'
replace_pages = '<field name="pages">'
replace_language = '<field name="language">'
replace_eng = 'English'
replace_call_num = '<field name="call_number">'
replace_notes = '<field name="notes">'
replace_custom1 = '<field name="state_country">'
replace_secondary_title = '<field name="series_title">'
replace_volume = '<field name="series_vol">'
replace_num_vols = '<field name="series_num_vol">'
replace_issue = '<field name="issue">'
replace_edition = '<field name="edition">'
replace_abstract = '<field name="abstract">'
replace_xml_close = '</add>'
replace_records_close = ''
replace_record_close = '</doc>'
replace_source_app = ''
replace_style_close = ''
replace_type_close = '</field>'
replace_contributors_close = ''
replace_translated_authors_close = '</field>'
replace_authors_close = ''
replace_author_close = '</field>'
replace_titles_close = ''
replace_title_close = '</field>'
replace_keywords_close = ''
replace_keyword_close = '</field>'
replace_dates_close = ''
replace_year_close = '</field>'
replace_pub_dates_close = ''
replace_date_close = '</field>'
replace_publisher_close = '</field>'
replace_pub_location_close = '</field>'
replace_pages_close = '</field>'
replace_language_close = '</field>'
replace_call_num_close = '</field>'
replace_notes_close = '</field>'
replace_custom1_close = '</field>'
replace_secondary_title_close = '</field>'
replace_volume_close = '</field>'
replace_num_vols_close = '</field>'
replace_issue_close = '</field>'
replace_edition_close = '</field>'
replace_abstract_close = '</field>'
replace_record_close = '</doc>'
replace_records_close = ''
replace_xml_close = '</add>'


#Doing replacements and saving files.
outdata = File.read(filename).gsub(/<xml>/, "#{replace_xml}").gsub(/<records>/, "#{replace_records}").gsub(/<record>/, "#{replace_record}").gsub(/<source-app name="Biblio" version="6.x">Drupal-Biblio<\/source-app>/, "#{replace_source_app}").gsub(/<style face="normal" font="default" size="100%">/, "#{replace_style}").gsub(/<ref-type>/, "#{replace_type}").gsub(/<contributors>/, "#{replace_contributors}").gsub(/<\/contributors>/, "#{replace_contributors_close}").gsub(/<\/ref-type>/, "#{replace_type_close}").gsub(/<\/style>/, "#{replace_style_close}").gsub(/<\/record>/, "#{replace_record_close}").gsub(/<\/records>/, "#{replace_records_close}").gsub(/<\/xml>/, "#{replace_xml_close}").gsub(/<translated-authors><author>/, "#{replace_translated_authors}").gsub(/<\/author><\/translated-authors>/, "#{replace_translated_authors_close}").gsub(/<authors>/, "#{replace_authors}").gsub(/<\/authors>/, "#{replace_authors_close}").gsub(/<titles>/, "#{replace_titles}").gsub(/<\/titles>/, "#{replace_titles_close}").gsub(/<title>/, "#{replace_title}").gsub(/<\/title>/, "#{replace_title_close}").gsub(/<keywords>/, "#{replace_keywords}").gsub(/<\/keywords>/, "#{replace_keywords_close}").gsub(/<keyword>/, "#{replace_keyword}").gsub(/<\/keyword>/, "#{replace_keyword_close}").gsub(/<dates>/, "#{replace_dates}").gsub(/<\/dates>/, "#{replace_dates_close}").gsub(/<year>/, "#{replace_year}").gsub(/<\/year>/, "#{replace_year_close}").gsub(/<pub-dates>/, "#{replace_pub_dates}").gsub(/<\/pub-dates>/, "#{replace_pub_dates_close}").gsub(/<date>/, "#{replace_date}").gsub(/<\/date>/, "#{replace_date_close}").gsub(/<publisher>/, "#{replace_publisher}").gsub(/<\/publisher>/, "#{replace_publisher_close}").gsub(/<pub-location>/, "#{replace_pub_location}").gsub(/<\/pub-location>/, "#{replace_pub_location_close}").gsub(/<pages>/, "#{replace_pages}").gsub(/<\/pages>/, "#{replace_pages_close}").gsub(/<language>/, "#{replace_language}").gsub(/<\/language>/, "#{replace_language_close}").gsub(/eng/, "#{replace_eng}").gsub(/<call-num>/, "#{replace_call_num}").gsub(/<\/call-num>/, "#{replace_call_num_close}").gsub(/<notes>/, "#{replace_notes}").gsub(/<\/notes>/, "#{replace_notes_close}").gsub(/<custom1>/, "#{replace_custom1}").gsub(/<\/custom1>/, "#{replace_custom1_close}").gsub(/<secondary-title>/, "#{replace_secondary_title}").gsub(/<\/secondary-title>/, "#{replace_secondary_title_close}").gsub(/<volume>/, "#{replace_volume}").gsub(/<\/volume>/, "#{replace_volume_close}").gsub(/<num-vols>/, "#{replace_num_vols}").gsub(/<\/num-vols>/, "#{replace_num_vols_close}").gsub(/<issue>/, "#{replace_issue}").gsub(/<\/issue>/, "#{replace_issue_close}").gsub(/<edition>/, "#{replace_edition}").gsub(/<\/edition>/, "#{replace_edition_close}").gsub(/<abstract>/, "#{replace_abstract}").gsub(/<\/abstract>/, "#{replace_abstract_close}").gsub(/<author>/, "#{replace_author}").gsub(/<\/author>/, "#{replace_author_close}")
File.open(filename, 'w') do |out|
  out << outdata
end  